# Generated by Django 5.2.17 on 2026-08-15 05:10

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='Optional PDF attachment for students/faculty to download (PDF only, max 5MB).', null=True, upload_to='notices/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed for notice attachments.'), apps.core.validators.validate_file_size_5mb], verbose_name='file attachment'),
        ),
    ]
