# Generated by Django 5.2.17 on 2026-08-15 05:21

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_is_active'),
        ('programs', '0002_alter_program_syllabus_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(blank=True, help_text='Official roll / admission number assigned by office staff after approval.', max_length=50, null=True, unique=True, verbose_name='admission number')),
                ('date_of_birth', models.DateField(blank=True, help_text="Student's date of birth (YYYY-MM-DD).", null=True, verbose_name='date of birth')),
                ('batch_year', models.CharField(blank=True, help_text="Academic batch session (e.g. '2024-2026').", max_length=20, verbose_name='batch year')),
                ('photo', models.ImageField(blank=True, help_text='Passport-sized photograph (max 5MB, JPG/PNG/WEBP).', null=True, upload_to='students/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Allowed image formats are JPG, JPEG, PNG, or WEBP.'), apps.core.validators.validate_file_size_5mb], verbose_name='passport photo')),
                ('address', models.TextField(blank=True, help_text="Student's current mailing or home address.", verbose_name='permanent / residential address')),
                ('guardian_name', models.CharField(blank=True, help_text='Full name of parent or legal guardian.', max_length=150, verbose_name='guardian / parent name')),
                ('guardian_phone', models.CharField(blank=True, help_text='Primary contact phone number of guardian.', max_length=20, verbose_name='guardian contact number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('program', models.ForeignKey(blank=True, help_text='The academic program the student is enrolled in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='programs.program', verbose_name='enrolled degree program')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
