# Generated by Django 5.2.17 on 2026-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('principal', 'Principal'), ('office_staff', 'Office Staff'), ('faculty', 'Faculty'), ('student', 'Student')], db_index=True, default='student', help_text="The user's functional role within the ERP.", max_length=20, verbose_name='role'),
        ),
    ]
