# Generated by Django 5.2.17 on 2026-08-15 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_target_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('office_staff', 'Office Staff'), ('faculty', 'Faculty'), ('student', 'Student')], help_text='Used only for broadcast announcements (recipient is None). Leave blank to broadcast to all roles.', max_length=20, verbose_name='broadcast target role')),
                ('subject', models.CharField(help_text='Brief subject or summary of the message.', max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='Plain-text message content.', verbose_name='message body')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sent at')),
                ('is_read', models.BooleanField(default=False, help_text='Tracks whether the direct recipient has opened the message.', verbose_name='is read')),
                ('recipient', models.ForeignKey(blank=True, help_text='Direct recipient user. Leave empty for administrative broadcast.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='msg_recipient_read_idx'), models.Index(fields=['sent_at'], name='msg_sent_at_idx')],
            },
        ),
    ]
