# Generated by Django 5.2.17 on 2026-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='broadcast_target_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('principal', 'Principal'), ('office_staff', 'Office Staff'), ('faculty', 'Faculty'), ('student', 'Student')], help_text='Used only for broadcast announcements (recipient is None). Leave blank to broadcast to all roles.', max_length=20, verbose_name='broadcast target role'),
        ),
    ]
