# Generated by Django 5.2.17 on 2026-08-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='website_url',
            field=models.URLField(blank=True, default='https://millathcollege.org', help_text='Official website address of the institution.', verbose_name='website URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_primary',
            field=models.EmailField(blank=True, default='millathcollege669@yahoo.com', help_text='Main contact email for public enquiries.', max_length=254, verbose_name='primary email'),
        ),
    ]
