# Generated by Django 5.2.17 on 2026-08-15 05:10

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='syllabus_pdf',
            field=models.FileField(blank=True, help_text='Optional PDF download of the detailed curriculum / syllabus (PDF only, max 5MB).', null=True, upload_to='programs/syllabus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Only PDF files are allowed for syllabus documents.'), apps.core.validators.validate_file_size_5mb], verbose_name='syllabus document'),
        ),
    ]
