# Generated by Django 5.2.17 on 2026-08-15 16:55

import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_alter_program_syllabus_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Clear and descriptive title of the coursework assignment.', max_length=255, verbose_name='assignment title')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed guidelines, questions, rubric, and submission requirements.', verbose_name='assignment instructions / description')),
                ('due_date', models.DateTimeField(help_text='Strict submission deadline for students.', verbose_name='due date & time')),
                ('max_marks', models.PositiveIntegerField(default=100, help_text='Total maximum points or score achievable for this assignment.', verbose_name='maximum marks')),
                ('attachment', models.FileField(blank=True, help_text='Optional reference document, rubric, or worksheet (PDF, DOC, DOCX up to 5MB).', null=True, upload_to='assignments/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'], message='Allowed file types are PDF, DOC, and DOCX.'), apps.core.validators.validate_file_size_5mb], verbose_name='assignment attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle whether students can view and submit to this assignment.', verbose_name='is active')),
                ('created_by', models.ForeignKey(help_text='Faculty member who created and oversees this assignment.', limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='faculty instructor')),
                ('program', models.ForeignKey(blank=True, help_text='Optionally restrict to an academic program / specialization. Leave empty for all students.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='programs.program', verbose_name='academic program')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(help_text='Upload your completed assignment file (Max 5MB; PDF, Word, or image).', upload_to='assignments/submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'], message='Allowed file formats are: PDF, DOC, DOCX, JPG, JPEG, and PNG.'), apps.core.validators.validate_file_size_5mb], verbose_name='submitted file')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
                ('marks_obtained', models.PositiveIntegerField(blank=True, help_text='Awarded score evaluated by the instructor.', null=True, verbose_name='marks obtained')),
                ('feedback', models.TextField(blank=True, help_text='Evaluator commentary, constructive feedback, or suggestions.', verbose_name='instructor feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='graded at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='graded by')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'Assignment Submission',
                'verbose_name_plural': 'Assignment Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
