# Generated by Django 5.2.17 on 2026-08-15 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0002_alter_program_syllabus_pdf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text="Course title or subject component (e.g., 'Pedagogy of Mathematics', 'ICT in Education').", max_length=200, verbose_name='course / subject name')),
                ('max_marks', models.PositiveIntegerField(default=20, help_text='Maximum achievable score for this internal assessment.', verbose_name='maximum marks')),
                ('marks_obtained', models.PositiveIntegerField(help_text='Score awarded to the student.', verbose_name='marks obtained')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='entered at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published')], db_index=True, default='draft', help_text='Current workflow status of this mark entry.', max_length=20, verbose_name='approval status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('review_comment', models.TextField(blank=True, help_text='Feedback provided by the reviewer (mandatory when rejecting marks to guide revisions).', verbose_name='review / rejection comment')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('entered_by', models.ForeignKey(help_text='Faculty instructor who evaluated and entered these marks.', limit_choices_to={'role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, related_name='entered_internal_marks', to=settings.AUTH_USER_MODEL, verbose_name='evaluating faculty')),
                ('program', models.ForeignKey(help_text='Academic degree program or specialization.', on_delete=django.db.models.deletion.PROTECT, related_name='internal_marks', to='programs.program', verbose_name='academic program')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Principal or administrator who approved or rejected these marks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_internal_marks', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('student', models.ForeignKey(help_text='Student receiving this internal evaluation score.', limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='internal_marks', to=settings.AUTH_USER_MODEL, verbose_name='student')),
            ],
            options={
                'verbose_name': 'Internal Assessment Mark',
                'verbose_name_plural': 'Internal Assessment Marks',
                'ordering': ['-entered_at'],
                'unique_together': {('student', 'program', 'subject')},
            },
        ),
    ]
